### ISSUE TITLE
tokenType id_token doesn't work

### ISSUE THREAD

**Issue by mookie5dc** [microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter#4]
I tried to set the tokenType in this client to "id_token" instead of the Bearer default.  It seems like that parameter is ignored and a Bearer token is always returned.

Additionally, is there a reason offline_access is always added?  I don't want to require my users to give offline access (online_access should be sufficient)

**Comment by unpluggedk** [comment]
hey there, 
first of all, this is a sample auth intended for graph authentication; so it is set by default to use Bearer, which is what graph client needs.

Anyways, tokenType is set at init (with the value of bearer as you mentioned), can you share how/where you are setting the "id_token" for the tokenType and what are you referring as a returned values? 
If you want to inject a custom header value or see how they are injected, please check appendAuthenticationHeaders in this branch [https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter/tree/adding_custom_headers]; namely this file [https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter/blob/adding_custom_headers/MSGraphSDKNXOAuth2/Auth/NXOAuth2AuthenticationProvider.m]

Offline_access is needed to persist the access token itself. without it, the app will ask for credential at each run of the application.

Does it make sense? Let me know if you have further questions !

Thanks

**Comment by mookie5dc** [comment]
Hi, thanks for the response!  I had overridden the tokenType value in the connectToGraphWithClientId call like so:

[NXOAuth2AuthenticationProvider sharedAuthProvider].tokenType = @"somethingamazing";

What I'd like to do is to authenticate a user via the OpenID Connect protocol to get an id_token back that I can send to my backend server to validate. 1) does the new Graph API support OpenID? 2) Is this library suitable for that authentication flow?

**Comment by unpluggedk** [comment]
Hi, 
1) the Graph API only works for Microsoft tenants. 
2) for a simple OpenID auth flow, I recommend using the more general [NXOAuth2Client](https://github.com/nxtbgthng/OAuth2Client), which is the base implementation of this repo

Hope it helps!

**Comment by mookie5dc** [comment]
Looks like this library isn't suited for what I want to do (NXOAuth2Client also doesn't support simple openid auth flow without changes).  Thanks for the help
