### ISSUE TITLE
Getting accessToken after successful authentication

### ISSUE THREAD

**Issue by alexziskind1** [microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter#5]
I'm able to successfully authenticate and use the graph SDK on iOS, but I would like to call the APIs via HTTP REST calls instead. For that I need the accessToken, but I don't see that it's accessible in this adapter and I can't help but think I'm missing something obvious. 
Is there a way to get the token from this lib? If not, then how is it possible to call the graph API via HTTP?

Thanks!

**Comment by mookie5dc** [comment]
You can query the account store for the MSGraph account type like so:

```
            NSArray* accounts = [[NXOAuth2AccountStore sharedStore] accountsWithAccountType:@"MSGraph"];
            if (accounts.count > 0) {
                NXOAuth2Account* account = [accounts objectAtIndex:0];
                NSLog(@"accessToken is %@", account.accessToken.accessToken);
            }
```

**Comment by unpluggedk** [comment]
Thanks @mookie5dc 

@alexziskind1 if you use this for REST, please know that there is a loginSilent method you could use for the subsequent logins, and also, there is a appendAuthenticationHeaders you can call before making the request.
Using the latter, it will append the needed header fields into the NSURLRequest.

**Comment by alexziskind1** [comment]
That did the trick! Thanks @mookie5dc !
Wish there was a simpler method though that didn't have magic strings, but this works.
@unpluggedk my use case is a bit strange, I'm using this in a javaScript app and importing the cocoapod while bridging it to JS. Some of the Graph APIs are a bit wacky when used this way, and I have to feel around for the right API to use (they don't match the docs exactly). So my next approach is to try pure rest calls in JS after authenticating with this lib.

**Comment by mookie5dc** [comment]
@alexziskind1 - you may want to use a different flow instead.  Check out the SPA flow here:
https://azure.microsoft.com/en-us/documentation/articles/active-directory-authentication-scenarios/#single-page-application-spa

**Comment by alexziskind1** [comment]
Unfortunately that version of ADAL depends on the browser and I'm using a
browserless environment.

On Jul 5, 2016, at 9:02 PM, Dale Chen notifications@github.com wrote:

@alexziskind1 https://github.com/alexziskind1 - you may want to use a
different flow instead. Check out the SPA flow here:
https://azure.microsoft.com/en-us/documentation/articles/active-directory-authentication-scenarios/#single-page-application-spa

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter/issues/5#issuecomment-230645565,
or mute the thread
https://github.com/notifications/unsubscribe/ABkAszKqZnmU14wBOyDtQhf4MmFd_4mhks5qSv6HgaJpZM4JCIbl
.
