### ISSUE TITLE
"Learn More" links not using HTTPS

### ISSUE THREAD

**Issue by wesley-dynamicowl** [microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter#7]
In the authorization controller, users can click "Other sign in Options" to view a page in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/19351307/20199431/5af5061a-a778-11e6-9175-8e9df04c52d7.png)

The "Learn More" link is HTTP. It should be HTTPS to comply with Apple's upcoming security requirements

**Comment by caitlinrussell** [comment]
This text does not belong to the adapter
